### ISSUE TITLE
Player board display

### ISSUE THREAD

**Issue by chloell5** [hschmid516/battleship#11]
Unable to transfer over player board display from player.rb to game.rb, using computer board display as placeholder for now.

**Comment by chloell5** [comment]
lib/player.rb:67:in `p_board': stack level too deep (SystemStackError)

I don't know how, but when it tries to render the board, it goes into a recursion loop until the program stops

**Comment by hschmid516** [comment]
Ugh I was getting stack level too deep also. And then I moved the com methods back over to Game and was still getting it...Trying to figure out what happened.
